[package]
name = "rboard"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["canvas"]}
iced_aw = { version = "0.12.2", default-features = false, features = ["menu"] }
